export const storageEnvironments = {
  STORAGE_ACCESS_KEY_ID: 'STORAGE_ACCESS_KEY_ID',
  STORAGE_SECRET_KEY_ID: 'STORAGE_SECRET_KEY_ID',
  STORAGE_ENDPOINT: 'STORAGE_ENDPOINT',
  STORAGE_REGION: 'STORAGE_REGION',
  STORAGE_BUCKET_NAME: 'STORAGE_BUCKET_NAME',
};
